In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    'Weight':[79,69,73,95,82,55,69,71,64,69],
    'Height':[1.80,1.68,1.82,1.70,1.87,1.55,1.50,1.78,1.67,1.64],
    'Age':[35,39,25,60,27,18,89,42,16,52],
    'Gender':['Male','Male','Male','Male','Male',
              'Female','Female','Female','Female','Female']
}

df = pd.DataFrame(data)

df

   Weight  Height  Age  Gender
0      79    1.80   35    Male
1      69    1.68   39    Male
2      73    1.82   25    Male
3      95    1.70   60    Male
4      82    1.87   27    Male
5      55    1.55   18  Female
6      69    1.50   89  Female
7      71    1.78   42  Female
8      64    1.67   16  Female
9      69    1.64   52  Female

In [ ]:
df['Gender'] = df['Gender'].map({
    'Male':1,
    'Female':0
})

df

   Weight  Height  Age  Gender
0      79    1.80   35       1
1      69    1.68   39       1
2      73    1.82   25       1
3      95    1.70   60       1
4      82    1.87   27       1
5      55    1.55   18       0
6      69    1.50   89       0
7      71    1.78   42       0
8      64    1.67   16       0
9      69    1.64   52       0

In [ ]:
X = df[['Height','Age','Gender']]
y = df['Weight']

print(X.head())
print(y.head())

   Height  Age  Gender
0    1.80   35       1
1    1.68   39       1
2    1.82   25       1
3    1.70   60       1
4    1.87   27       1
0    79
1    69
2    73
3    95
4    82
Name: Weight, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (8, 3)
Testing Data: (2, 3)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Training Completed")

Training Completed

In [ ]:
y_pred = model.predict(X_test)

print("Predicted Values:")
print(y_pred)

print("\nActual Values:")
print(y_test.values)

Predicted Values:
[56.85651025 79.10576115]

Actual Values:
[64 69]

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE =", mae)
print("R2 Score =", r2)

MAE = 8.624625451606978
R2 Score = -11.252468343750825

In [ ]:
sample = pd.DataFrame({
    'Height':[1.75],
    'Age':[30],
    'Gender':[1]
})

predicted_weight = model.predict(sample)

print("Predicted Weight =", predicted_weight[0], "kg")

Predicted Weight = 78.548582018849 kg

In [ ]:
print("Linear Regression model successfully predicts body weight using Height, Age, and Gender.")

Linear Regression model successfully predicts body weight using Height, Age, and Gender.